apiVersion: v1
kind: PersistentVolume
metadata:
  name: website-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/c/Users/WIN10/Desktop/ArchivosCloud/static-website"
